version: '3.8'
services:
  web:
    build: .
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - gjnet

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - gjnet

  nginx:
    image: nginx:latest
    container_name: gratitude_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - gjnet

volumes:
  pgdata:

networks:
  gjnet:
    driver: bridge

  